name: sms_reader
description: A Flutter plugin to read past and incoming SMS messages with advanced filtering.
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  sms_reader_platform_interface:
    path: ../sms_reader_platform_interface
  sms_reader_android:
    path: ../sms_reader_android
  sms_reader_ios:
    path: ../sms_reader_ios

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  plugin_platform_interface: ^2.1.8

flutter:
  plugin:
    platforms:
      android:
        default_package: sms_reader_android
      ios:
        default_package: sms_reader_ios
